import type { ModuleConfig, LayoutType } from '@/types/module'

const statusOptions = {
  sales: ['pending', 'completed', 'cancelled', 'draft'],
  invoice: ['pending', 'completed', 'overdue', 'draft'],
  purchase: ['pending', 'approved', 'completed', 'cancelled'],
  inventory: ['active', 'low_stock'],
  route: ['active', 'completed', 'pending', 'in_transit'],
  hr: ['active', 'pending', 'approved', 'rejected'],
  logistics: ['pending', 'in_transit', 'delivered', 'cancelled'],
  ledger: ['completed', 'pending', 'draft'],
  tracking: ['active', 'idle', 'offline'],
  settings: ['active'],
} as const

function cfg(
  slug: string,
  title: string,
  layout: LayoutType,
  domain: string,
  overrides: Partial<ModuleConfig> = {},
): ModuleConfig {
  const defaults: Record<LayoutType, Partial<ModuleConfig>> = {
    transaction: {
      subtitle: `Manage ${title.toLowerCase()} and track transactions`,
      columns: [
        { field: 'code', header: 'Code', width: 130 },
        { field: 'customer', header: 'Customer', flex: 1 },
        { field: 'salesman', header: 'Salesman', width: 140 },
        { field: 'date', header: 'Date', type: 'date', width: 110 },
        { field: 'amount', header: 'Amount', type: 'currency', width: 120 },
        { field: 'status', header: 'Status', type: 'status', width: 120 },
      ],
      stats: [
        { key: 'total', label: 'Total Records', format: 'number' },
        { key: 'totalAmount', label: 'Total Value', format: 'currency' },
        { key: 'pending', label: 'Pending', format: 'number' },
        { key: 'completed', label: 'Completed', format: 'number' },
      ],
      formFields: [
        { name: 'customer', label: 'Customer', type: 'text', required: true },
        { name: 'amount', label: 'Amount', type: 'number', required: true },
        { name: 'date', label: 'Date', type: 'date', required: true },
        { name: 'status', label: 'Status', type: 'select', options: statusOptions.sales.map((v) => ({ value: v, label: v })) },
      ],
      chartType: 'area', chartTitle: `${title} Trend`, showChart: true,
    },
    report: {
      subtitle: `Analytical report for ${title.toLowerCase()}`,
      columns: [
        { field: 'code', header: 'Ref', width: 120 },
        { field: 'particulars', header: 'Description', flex: 1 },
        { field: 'date', header: 'Period', type: 'date', width: 110 },
        { field: 'debit', header: 'Debit', type: 'currency', width: 120 },
        { field: 'credit', header: 'Credit', type: 'currency', width: 120 },
        { field: 'status', header: 'Status', type: 'status', width: 110 },
      ],
      stats: [
        { key: 'totalDebit', label: 'Total Debit', format: 'currency' },
        { key: 'totalCreditBal', label: 'Total Credit', format: 'currency' },
        { key: 'total', label: 'Entries', format: 'number' },
        { key: 'pending', label: 'Pending', format: 'number' },
      ],
      formFields: [],
      chartType: 'bar', chartTitle: `${title} Analysis`, showChart: true,
      features: ['reportTotals'],
    },
    ledger: {
      subtitle: `Financial ledger entries for ${title.toLowerCase()}`,
      columns: [
        { field: 'code', header: 'Voucher', width: 120 },
        { field: 'date', header: 'Date', type: 'date', width: 110 },
        { field: 'account', header: 'Account', flex: 1 },
        { field: 'particulars', header: 'Particulars', width: 140 },
        { field: 'debit', header: 'Debit', type: 'currency', width: 110 },
        { field: 'credit', header: 'Credit', type: 'currency', width: 110 },
        { field: 'balance', header: 'Balance', type: 'currency', width: 120 },
      ],
      stats: [
        { key: 'totalDebit', label: 'Total Debit', format: 'currency' },
        { key: 'totalCreditBal', label: 'Total Credit', format: 'currency' },
        { key: 'total', label: 'Entries', format: 'number' },
        { key: 'pending', label: 'Unposted', format: 'number' },
      ],
      formFields: [
        { name: 'account', label: 'Account', type: 'text', required: true },
        { name: 'debit', label: 'Debit', type: 'number' },
        { name: 'credit', label: 'Credit', type: 'number' },
        { name: 'date', label: 'Date', type: 'date', required: true },
      ],
      chartType: 'line', showChart: false,
    },
    inventory: {
      subtitle: `Stock and product management for ${title.toLowerCase()}`,
      columns: [
        { field: 'code', header: 'SKU', width: 120 },
        { field: 'name', header: 'Product', flex: 1 },
        { field: 'category', header: 'Category', width: 120 },
        { field: 'brand', header: 'Brand', width: 100 },
        { field: 'stock', header: 'Stock', type: 'number', width: 90 },
        { field: 'mrp', header: 'MRP', type: 'currency', width: 100 },
        { field: 'status', header: 'Status', type: 'status', width: 110 },
      ],
      stats: [
        { key: 'total', label: 'Products', format: 'number' },
        { key: 'totalStock', label: 'Total Stock', format: 'number' },
        { key: 'lowStock', label: 'Low Stock', format: 'number' },
        { key: 'totalAmount', label: 'Stock Value', format: 'currency' },
      ],
      formFields: [
        { name: 'name', label: 'Product Name', type: 'text', required: true },
        { name: 'category', label: 'Category', type: 'text' },
        { name: 'stock', label: 'Stock Qty', type: 'number' },
        { name: 'mrp', label: 'MRP', type: 'number' },
      ],
      chartType: 'bar', chartTitle: 'Stock Movement', showChart: true,
    },
    route: {
      subtitle: `Route operations and field sales for ${title.toLowerCase()}`,
      columns: [
        { field: 'code', header: 'Route', width: 100 },
        { field: 'name', header: 'Route Name', flex: 1 },
        { field: 'salesman', header: 'Salesman', width: 140 },
        { field: 'outlets', header: 'Outlets', type: 'number', width: 90 },
        { field: 'visited', header: 'Visited', type: 'number', width: 90 },
        { field: 'collections', header: 'Collection', type: 'currency', width: 120 },
        { field: 'status', header: 'Status', type: 'status', width: 110 },
      ],
      stats: [
        { key: 'total', label: 'Routes', format: 'number' },
        { key: 'completed', label: 'Completed', format: 'number' },
        { key: 'totalAmount', label: 'Total Sales', format: 'currency' },
        { key: 'pending', label: 'In Progress', format: 'number' },
      ],
      formFields: [
        { name: 'name', label: 'Route Name', type: 'text', required: true },
        { name: 'salesman', label: 'Salesman', type: 'text', required: true },
        { name: 'outlets', label: 'Outlets', type: 'number' },
      ],
      chartType: 'area', chartTitle: 'Route Performance', showChart: true,
    },
    hr: {
      subtitle: `Workforce management for ${title.toLowerCase()}`,
      columns: [
        { field: 'code', header: 'ID', width: 100 },
        { field: 'name', header: 'Employee', flex: 1 },
        { field: 'department', header: 'Department', width: 120 },
        { field: 'role', header: 'Role', width: 140 },
        { field: 'salary', header: 'Salary', type: 'currency', width: 110 },
        { field: 'attendance', header: 'Attendance', width: 110 },
        { field: 'status', header: 'Status', type: 'status', width: 110 },
      ],
      stats: [
        { key: 'total', label: 'Employees', format: 'number' },
        { key: 'active', label: 'Active', format: 'number' },
        { key: 'totalAmount', label: 'Payroll', format: 'currency' },
        { key: 'pending', label: 'On Leave', format: 'number' },
      ],
      formFields: [
        { name: 'name', label: 'Name', type: 'text', required: true },
        { name: 'department', label: 'Department', type: 'text' },
        { name: 'role', label: 'Role', type: 'text' },
        { name: 'salary', label: 'Salary', type: 'number' },
      ],
      chartType: 'donut', chartTitle: 'Department Distribution', showChart: true,
    },
    customer: {
      subtitle: `Customer relationship management for ${title.toLowerCase()}`,
      columns: [
        { field: 'code', header: 'Code', width: 110 },
        { field: 'name', header: 'Customer', flex: 1 },
        { field: 'route', header: 'Route', width: 140 },
        { field: 'creditLimit', header: 'Credit Limit', type: 'currency', width: 120 },
        { field: 'outstanding', header: 'Outstanding', type: 'currency', width: 120 },
        { field: 'lastVisit', header: 'Last Visit', type: 'date', width: 110 },
        { field: 'status', header: 'Status', type: 'status', width: 110 },
      ],
      stats: [
        { key: 'total', label: 'Customers', format: 'number' },
        { key: 'totalOutstanding', label: 'Outstanding', format: 'currency' },
        { key: 'totalCredit', label: 'Credit Limit', format: 'currency' },
        { key: 'overdue', label: 'Overdue', format: 'number' },
      ],
      formFields: [
        { name: 'name', label: 'Customer Name', type: 'text', required: true },
        { name: 'route', label: 'Route', type: 'text' },
        { name: 'creditLimit', label: 'Credit Limit', type: 'number' },
        { name: 'phone', label: 'Phone', type: 'text' },
      ],
      chartType: 'area', chartTitle: 'Customer Activity', showChart: true,
    },
    logistics: {
      subtitle: `Delivery and fleet management for ${title.toLowerCase()}`,
      columns: [
        { field: 'code', header: 'Delivery', width: 120 },
        { field: 'vehicle', header: 'Vehicle', width: 130 },
        { field: 'driver', header: 'Driver', width: 140 },
        { field: 'customer', header: 'Customer', flex: 1 },
        { field: 'distance', header: 'Distance', width: 100 },
        { field: 'amount', header: 'Value', type: 'currency', width: 110 },
        { field: 'status', header: 'Status', type: 'status', width: 110 },
      ],
      stats: [
        { key: 'total', label: 'Deliveries', format: 'number' },
        { key: 'inTransit', label: 'In Transit', format: 'number' },
        { key: 'completed', label: 'Delivered', format: 'number' },
        { key: 'totalAmount', label: 'Total Value', format: 'currency' },
      ],
      formFields: [
        { name: 'vehicle', label: 'Vehicle', type: 'text', required: true },
        { name: 'driver', label: 'Driver', type: 'text' },
        { name: 'customer', label: 'Customer', type: 'text' },
      ],
      chartType: 'bar', chartTitle: 'Delivery Volume', showChart: true,
    },
    settings: {
      subtitle: `System configuration for ${title.toLowerCase()}`,
      columns: [
        { field: 'code', header: 'Key', width: 100 },
        { field: 'name', header: 'Setting', flex: 1 },
        { field: 'value', header: 'Value', width: 200 },
        { field: 'category', header: 'Category', width: 120 },
        { field: 'updatedBy', header: 'Updated By', width: 140 },
        { field: 'date', header: 'Modified', type: 'date', width: 110 },
      ],
      stats: [
        { key: 'total', label: 'Settings', format: 'number' },
        { key: 'active', label: 'Active', format: 'number' },
      ],
      formFields: [
        { name: 'name', label: 'Setting Name', type: 'text', required: true },
        { name: 'value', label: 'Value', type: 'text', required: true },
        { name: 'category', label: 'Category', type: 'text' },
      ],
      showChart: false,
    },
    tracking: {
      subtitle: `Live GPS tracking for ${title.toLowerCase()}`,
      columns: [
        { field: 'code', header: 'ID', width: 90 },
        { field: 'salesman', header: 'Salesman', width: 140 },
        { field: 'route', header: 'Route', flex: 1 },
        { field: 'outlet', header: 'Current Outlet', width: 160 },
        { field: 'speed', header: 'Speed', width: 90 },
        { field: 'battery', header: 'Battery', width: 90 },
        { field: 'status', header: 'Status', type: 'status', width: 100 },
      ],
      stats: [
        { key: 'active', label: 'Online', format: 'number' },
        { key: 'total', label: 'Tracked', format: 'number' },
        { key: 'pending', label: 'Idle', format: 'number' },
        { key: 'completed', label: 'Checked In', format: 'number' },
      ],
      formFields: [],
      showChart: false,
    },
  }

  const base = defaults[layout]
  return {
    slug,
    title,
    layout,
    domain,
    entityName: title.replace(/s$/, ''),
    accentColor: 'var(--rs-primary)',
    statuses: [...(statusOptions[domain as keyof typeof statusOptions] ?? statusOptions.sales)],
    ...base,
    ...overrides,
  } as ModuleConfig
}

// Build registry from navigation paths
const registryEntries: [string, string, LayoutType, string, Partial<ModuleConfig>?][] = [
  // Sales
  ['sales-orders', 'Orders', 'transaction', 'sales', { documentedFlow: 'new-order' as const }],
  ['sales-invoices', 'Invoices', 'transaction', 'invoice', { columns: [
    { field: 'code', header: 'Invoice', width: 120 }, { field: 'customer', header: 'Customer', flex: 1 },
    { field: 'date', header: 'Date', type: 'date', width: 110 }, { field: 'dueDate', header: 'Due Date', type: 'date', width: 110 },
    { field: 'total', header: 'Total', type: 'currency', width: 120 }, { field: 'status', header: 'Status', type: 'status', width: 110 },
  ]}],
  ['sales-sales-return', 'Sales Returns', 'transaction', 'sales', { documentedFlow: 'sales-return' as const }],
  ['sales-credit-notes', 'Credit Notes', 'transaction', 'invoice'],
  ['sales-quotations', 'Quotations', 'transaction', 'sales', { subtitle: 'Create and manage sales quotations' }],
  ['sales-billing', 'Billing', 'transaction', 'invoice'],
  ['sales-route-sales', 'Route Sales', 'route', 'route'],
  ['sales-sales-report', 'Sales Report', 'report', 'sales', {
    columns: [
      { field: 'code', header: 'Order No.', width: 120 },
      { field: 'customer', header: 'Customer Name', flex: 1 },
      { field: 'salesman', header: 'Salesperson Name', width: 150 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'quantity', header: 'Qty', type: 'number', width: 80 },
      { field: 'amount', header: 'Amount', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['quantity', 'amount'],
  }],
  ['sales-customer-ledger', 'Customer Ledger', 'ledger', 'ledger'],
  ['sales-collection-report', 'Collection Report', 'report', 'ledger', {
    columns: [
      { field: 'code', header: 'Ref', width: 120 },
      { field: 'customer', header: 'Customer', flex: 1 },
      { field: 'route', header: 'Route', width: 140 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'amount', header: 'Collected', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['amount'],
  }],
  // Accounting
  ['accounting-transactions', 'Transactions', 'ledger', 'ledger'],
  ['accounting-day-book', 'Day Book', 'ledger', 'ledger'],
  ['accounting-cash-book', 'Cash Book', 'ledger', 'ledger'],
  ['accounting-bank-book', 'Bank Book', 'ledger', 'ledger'],
  ['accounting-journal-entries', 'Journal Entries', 'ledger', 'ledger'],
  ['accounting-ledger', 'Ledger', 'ledger', 'ledger', {
    subtitle: 'Create and manage ledger accounts',
    columns: [
      { field: 'code', header: 'Code', width: 100 },
      { field: 'ledgerTitle', header: 'Ledger Title', flex: 1 },
      { field: 'subGroup', header: 'Sub Group', width: 130 },
      { field: 'accountHead', header: 'Account Head', width: 140 },
      { field: 'description', header: 'Description', width: 160 },
      { field: 'balance', header: 'Balance', type: 'currency', width: 110 },
      { field: 'status', header: 'Status', type: 'status', width: 100 },
    ],
    formFields: [
      { name: 'ledgerTitle', label: 'Ledger Title', type: 'text', required: true },
      { name: 'subGroup', label: 'Sub Group', type: 'select', required: true, options: [
        { value: 'Current Assets', label: 'Current Assets' },
        { value: 'Fixed Assets', label: 'Fixed Assets' },
        { value: 'Current Liabilities', label: 'Current Liabilities' },
        { value: 'Income', label: 'Income' },
        { value: 'Expenses', label: 'Expenses' },
      ]},
      { name: 'accountHead', label: 'Account Head', type: 'select', required: true, options: [
        { value: 'Assets', label: 'Assets' },
        { value: 'Liabilities', label: 'Liabilities' },
        { value: 'Income', label: 'Income' },
        { value: 'Expenses', label: 'Expenses' },
        { value: 'Equity', label: 'Equity' },
      ]},
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    entityName: 'Ledger',
    showChart: false,
  }],
  ['accounting-trial-balance', 'Trial Balance', 'report', 'ledger', { showChart: true, chartType: 'bar', chartTitle: 'Account Balances' }],
  ['accounting-profit-loss', 'Profit & Loss', 'report', 'ledger', { chartType: 'area', chartTitle: 'P&L Trend', features: ['reportTotals', 'chartTypeSwitch'], sumFields: ['debit', 'credit'] }],
  ['accounting-balance-sheet', 'Balance Sheet', 'report', 'ledger', { showChart: true, chartType: 'donut', chartTitle: 'Asset Distribution' }],
  ['accounting-receipt-voucher', 'Receipt Voucher', 'ledger', 'ledger', {
    columns: [
      { field: 'code', header: 'Voucher No.', width: 120 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'account', header: 'Account', flex: 1 },
      { field: 'narration', header: 'Narration', width: 180 },
      { field: 'credit', header: 'Amount', type: 'currency', width: 110 },
      { field: 'status', header: 'Status', type: 'status', width: 100 },
    ],
    formFields: [
      { name: 'account', label: 'Account', type: 'text', required: true },
      { name: 'credit', label: 'Amount', type: 'number', required: true },
      { name: 'narration', label: 'Narration', type: 'textarea', required: true },
      { name: 'date', label: 'Date', type: 'date', required: true },
    ],
    entityName: 'Receipt Voucher',
  }],
  ['accounting-payment-voucher', 'Payment Voucher', 'ledger', 'ledger', {
    columns: [
      { field: 'code', header: 'Voucher No.', width: 120 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'account', header: 'Account', flex: 1 },
      { field: 'narration', header: 'Narration', width: 180 },
      { field: 'debit', header: 'Amount', type: 'currency', width: 110 },
      { field: 'status', header: 'Status', type: 'status', width: 100 },
    ],
    formFields: [
      { name: 'account', label: 'Account', type: 'text', required: true },
      { name: 'debit', label: 'Amount', type: 'number', required: true },
      { name: 'narration', label: 'Narration', type: 'textarea', required: true },
      { name: 'date', label: 'Date', type: 'date', required: true },
    ],
    entityName: 'Payment Voucher',
  }],
  ['accounting-contra-voucher', 'Contra Voucher', 'ledger', 'ledger'],
  ['accounting-purchase-report', 'Purchase Report', 'report', 'purchase', {
    columns: [
      { field: 'code', header: 'PO Ref', width: 120 },
      { field: 'supplier', header: 'Supplier', flex: 1 },
      { field: 'particulars', header: 'Description', width: 180 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'items', header: 'Items', type: 'number', width: 80 },
      { field: 'amount', header: 'Amount', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['items', 'amount'],
  }],
  ['accounting-sales-report', 'Sales Report', 'report', 'sales', {
    columns: [
      { field: 'code', header: 'Order No.', width: 120 },
      { field: 'customer', header: 'Customer Name', flex: 1 },
      { field: 'salesman', header: 'Salesperson Name', width: 150 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'quantity', header: 'Qty', type: 'number', width: 80 },
      { field: 'amount', header: 'Amount', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['quantity', 'amount'],
  }],
  ['accounting-supplier-settlement', 'Supplier Settlement', 'ledger', 'purchase'],
  ['accounting-customer-settlement', 'Customer Settlement', 'ledger', 'ledger'],
  ['accounting-outstanding-report', 'Outstanding Report', 'report', 'ledger', {
    columns: [
      { field: 'code', header: 'Ref', width: 120 },
      { field: 'customer', header: 'Customer', flex: 1 },
      { field: 'date', header: 'As On', type: 'date', width: 110 },
      { field: 'outstanding', header: 'Outstanding', type: 'currency', width: 130 },
      { field: 'creditLimit', header: 'Credit Limit', type: 'currency', width: 130 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['outstanding', 'creditLimit'],
  }],
  ['accounting-gst-report', 'GST Report', 'report', 'ledger', { columns: [
    { field: 'code', header: 'GST Ref', width: 100 }, { field: 'period', header: 'Period', width: 100 },
    { field: 'party', header: 'Party', flex: 1 }, { field: 'taxable', header: 'Taxable', type: 'currency', width: 110 },
    { field: 'cgst', header: 'CGST', type: 'currency', width: 90 }, { field: 'sgst', header: 'SGST', type: 'currency', width: 90 },
    { field: 'total', header: 'Total', type: 'currency', width: 110 },
  ]}],
  ['accounting-tax-summary', 'Tax Summary', 'report', 'ledger', {
    columns: [
      { field: 'code', header: 'Ref', width: 120 },
      { field: 'particulars', header: 'Tax Head', flex: 1 },
      { field: 'date', header: 'Period', type: 'date', width: 110 },
      { field: 'debit', header: 'Payable', type: 'currency', width: 120 },
      { field: 'credit', header: 'Receivable', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    features: ['reportTotals'],
    sumFields: ['debit', 'credit'],
  }],
  // Purchase
  ['purchase-purchase-orders', 'Purchase Orders', 'transaction', 'purchase', {
    documentedFlow: 'purchase-order' as const,
    columns: [
      { field: 'code', header: 'PO Number', width: 120 },
      { field: 'supplier', header: 'Supplier Name', flex: 1 },
      { field: 'productList', header: 'Product List', width: 220 },
      { field: 'totalQuantity', header: 'Quantity', type: 'number', width: 100 },
      { field: 'amount', header: 'Total Purchase', type: 'currency', width: 130 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    formFields: [],
    entityName: 'Purchase Order',
  }],
  ['purchase-purchases', 'Purchases', 'transaction', 'purchase'],
  ['purchase-supplier-management', 'Suppliers', 'customer', 'purchase', { entityName: 'Supplier' }],
  ['purchase-supplier-settlement', 'Supplier Settlement', 'ledger', 'purchase'],
  ['purchase-purchase-return', 'Purchase Returns', 'transaction', 'purchase'],
  ['purchase-purchase-report', 'Purchase Report', 'report', 'purchase', {
    columns: [
      { field: 'code', header: 'PO Ref', width: 120 },
      { field: 'supplier', header: 'Supplier', flex: 1 },
      { field: 'particulars', header: 'Description', width: 180 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'items', header: 'Items', type: 'number', width: 80 },
      { field: 'amount', header: 'Amount', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['items', 'amount'],
  }],
  // Inventory
  ['inventory-product-catalog', 'Product Catalog', 'inventory', 'inventory', {
    documentedFlow: 'product-catalog' as const,
    columns: [
      { field: 'code', header: 'SKU', width: 110 },
      { field: 'name', header: 'Product', flex: 1 },
      { field: 'category', header: 'Category', width: 110 },
      { field: 'brand', header: 'Brand', width: 90 },
      { field: 'stock', header: 'Stock', type: 'number', width: 80 },
      { field: 'mrp', header: 'MRP', type: 'currency', width: 100 },
      { field: 'status', header: 'Status', type: 'status', width: 100 },
    ],
    formFields: [
      { name: 'name', label: 'Product Name', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'brand', label: 'Brand', type: 'text' },
      { name: 'stock', label: 'Stock Qty', type: 'number' },
      { name: 'mrp', label: 'MRP', type: 'number' },
      { name: 'image', label: 'Product Image', type: 'image', helperText: 'Upload product image (JPG, PNG)' },
    ],
  }],
  ['inventory-categories', 'Categories', 'inventory', 'inventory'],
  ['inventory-brands', 'Brands', 'inventory', 'inventory'],
  ['inventory-units', 'Units', 'settings', 'inventory'],
  ['inventory-warehouse', 'Warehouses', 'inventory', 'inventory', {
    documentedFlow: 'stock-management' as const,
    features: ['warehouseTransfer'],
    columns: [
      { field: 'code', header: 'Code', width: 100 },
      { field: 'name', header: 'Warehouse', flex: 1 },
      { field: 'location', header: 'Location', width: 140 },
      { field: 'stockRooms', header: 'Stock Rooms', type: 'number', width: 100 },
      { field: 'stock', header: 'Total Stock', type: 'number', width: 100 },
      { field: 'status', header: 'Status', type: 'status', width: 100 },
    ],
    formFields: [
      { name: 'name', label: 'Warehouse Name', type: 'text', required: true },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'stockRooms', label: 'Stock Rooms', type: 'number' },
    ],
    entityName: 'Warehouse',
  }],
  ['inventory-stock-allocation', 'Stock Allocation', 'inventory', 'inventory', {
    documentedFlow: 'stock-allocation' as const,
    features: ['stockBatchAllocation'],
    columns: [
      { field: 'code', header: 'SKU', width: 110 },
      { field: 'name', header: 'Product', flex: 1 },
      { field: 'batch', header: 'Batch No.', width: 100 },
      { field: 'batchDate', header: 'Batch Date', type: 'date', width: 110 },
      { field: 'batchStockCount', header: 'Batch Stock', type: 'number', width: 100 },
      { field: 'warehouse', header: 'Warehouse', width: 130 },
      { field: 'stock', header: 'Allocated', type: 'number', width: 90 },
      { field: 'status', header: 'Status', type: 'status', width: 100 },
    ],
    formFields: [
      { name: 'name', label: 'Product', type: 'text', required: true },
      { name: 'batch', label: 'Batch Selection', type: 'select', required: true, options: [
        { value: 'B1001', label: 'B1001 — Sunflower Oil 5L' },
        { value: 'B1002', label: 'B1002 — Basmati Rice 10kg' },
        { value: 'B1003', label: 'B1003 — Mineral Water 1L' },
        { value: 'B1004', label: 'B1004 — Milk 500ml' },
      ]},
      { name: 'batchStockCount', label: 'Batch Stock Count', type: 'readonly', helperText: 'Available stock in selected batch' },
      { name: 'batchDate', label: 'Batch Date', type: 'date' },
      { name: 'warehouse', label: 'Warehouse', type: 'select', options: [
        { value: 'Main Warehouse', label: 'Main Warehouse' },
        { value: 'Cold Storage', label: 'Cold Storage' },
        { value: 'Depot North', label: 'Depot North' },
        { value: 'Depot South', label: 'Depot South' },
      ]},
      { name: 'stock', label: 'Allocate Qty', type: 'number', required: true },
    ],
    entityName: 'Allocation',
  }],
  ['inventory-stock-transfer', 'Stock Transfer', 'inventory', 'inventory'],
  ['inventory-stock-adjustment', 'Stock Adjustment', 'inventory', 'inventory'],
  ['inventory-stock-movement', 'Stock Movement', 'inventory', 'inventory'],
  ['inventory-low-stock', 'Low Stock', 'inventory', 'inventory'],
  ['inventory-batch-management', 'Batch Management', 'inventory', 'inventory', {
    columns: [
      { field: 'code', header: 'SKU', width: 110 },
      { field: 'name', header: 'Product', flex: 1 },
      { field: 'batch', header: 'Batch No.', width: 100 },
      { field: 'batchDate', header: 'Batch Date', type: 'date', width: 110 },
      { field: 'batchStockCount', header: 'Batch Stock', type: 'number', width: 110 },
      { field: 'expiry', header: 'Expiry Date', type: 'date', width: 110 },
      { field: 'status', header: 'Status', type: 'status', width: 100 },
    ],
    formFields: [
      { name: 'name', label: 'Product Name', type: 'text', required: true },
      { name: 'batch', label: 'Batch No.', type: 'text', required: true },
      { name: 'batchDate', label: 'Batch Date', type: 'date', required: true },
      { name: 'batchStockCount', label: 'Batch Stock Count', type: 'number', required: true },
      { name: 'expiry', label: 'Expiry Date', type: 'date' },
    ],
    entityName: 'Batch',
  }],
  ['inventory-expiry-report', 'Expiry Report', 'report', 'inventory', {
    columns: [
      { field: 'code', header: 'SKU', width: 110 },
      { field: 'name', header: 'Product', flex: 1 },
      { field: 'batch', header: 'Batch', width: 100 },
      { field: 'expiry', header: 'Expiry Date', type: 'date', width: 110 },
      { field: 'daysRemaining', header: 'Days Left', type: 'number', width: 90 },
      { field: 'stock', header: 'Qty', type: 'number', width: 80 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['stock'],
  }],
  // Stock Management (top-level module)
  ['stock-management-current-stock', 'Current Stock', 'inventory', 'inventory', {
    subtitle: 'Real-time view of stock levels across all warehouses',
    columns: [
      { field: 'code', header: 'SKU', width: 110 },
      { field: 'name', header: 'Product', flex: 1 },
      { field: 'category', header: 'Category', width: 120 },
      { field: 'brand', header: 'Brand', width: 100 },
      { field: 'warehouse', header: 'Warehouse', width: 140 },
      { field: 'stock', header: 'Current Stock', type: 'number', width: 120 },
      { field: 'minStock', header: 'Reorder Level', type: 'number', width: 120 },
      { field: 'mrp', header: 'Unit Price', type: 'currency', width: 110 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    stats: [
      { key: 'total', label: 'Total Products', format: 'number' },
      { key: 'totalStock', label: 'Total Stock Units', format: 'number' },
      { key: 'lowStock', label: 'Low Stock Items', format: 'number' },
      { key: 'totalAmount', label: 'Total Stock Value', format: 'currency' },
    ],
    formFields: [],
    statuses: ['active', 'low_stock', 'overdue'],
    chartType: 'bar', chartTitle: 'Stock Level Overview', showChart: true,
    entityName: 'Stock Record',
  }],
  ['stock-management-stock-adjustment', 'Stock Adjustment', 'transaction', 'inventory', {
    subtitle: 'Record manual stock additions, removals, and corrections',
    columns: [
      { field: 'code', header: 'Adj. ID', width: 120 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'name', header: 'Product', flex: 1 },
      { field: 'warehouse', header: 'Warehouse', width: 140 },
      { field: 'adjustmentType', header: 'Type', width: 110 },
      { field: 'quantity', header: 'Quantity', type: 'number', width: 100 },
      { field: 'reason', header: 'Reason', width: 160 },
      { field: 'adjustedBy', header: 'Adjusted By', width: 130 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    stats: [
      { key: 'total', label: 'Total Adjustments', format: 'number' },
      { key: 'pending', label: 'Pending', format: 'number' },
      { key: 'completed', label: 'Approved', format: 'number' },
      { key: 'totalStock', label: 'Units Adjusted', format: 'number' },
    ],
    formFields: [
      { name: 'name', label: 'Product', type: 'text', required: true },
      { name: 'warehouse', label: 'Warehouse', type: 'select', required: true, options: [
        { value: 'Main Warehouse', label: 'Main Warehouse' },
        { value: 'Cold Storage', label: 'Cold Storage' },
        { value: 'Depot North', label: 'Depot North' },
        { value: 'Depot South', label: 'Depot South' },
      ]},
      { name: 'adjustmentType', label: 'Adjustment Type', type: 'select', required: true, options: [
        { value: 'Addition', label: 'Addition (Stock In)' },
        { value: 'Removal', label: 'Removal (Stock Out)' },
        { value: 'Correction', label: 'Correction' },
        { value: 'Damage', label: 'Damage / Loss' },
        { value: 'Return', label: 'Return' },
      ]},
      { name: 'quantity', label: 'Quantity', type: 'number', required: true },
      { name: 'reason', label: 'Reason', type: 'select', options: [
        { value: 'Physical Count', label: 'Physical Count Variance' },
        { value: 'Damaged Goods', label: 'Damaged Goods' },
        { value: 'Theft / Loss', label: 'Theft / Loss' },
        { value: 'Supplier Return', label: 'Supplier Return' },
        { value: 'System Error', label: 'System Error Correction' },
        { value: 'Other', label: 'Other' },
      ]},
      { name: 'adjustedBy', label: 'Adjusted By', type: 'text' },
      { name: 'date', label: 'Date', type: 'date', required: true },
    ],
    entityName: 'Adjustment',
    statuses: ['pending', 'approved', 'completed', 'cancelled'],
    chartType: 'bar', chartTitle: 'Adjustment Trend', showChart: true,
  }],
  ['stock-management-stock-transfer', 'Stock Transfer', 'transaction', 'inventory', {
    subtitle: 'Transfer stock between warehouses and branches',
    documentedFlow: 'stock-transfer' as const,
    columns: [
      { field: 'code', header: 'Transfer ID', width: 130 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'sourceWarehouse', header: 'Source Warehouse', width: 150 },
      { field: 'destinationWarehouse', header: 'Destination', width: 150 },
      { field: 'productCount', header: 'Products', type: 'number', width: 90 },
      { field: 'totalQuantity', header: 'Total Qty', type: 'number', width: 100 },
      { field: 'requestedBy', header: 'Requested By', width: 130 },
      { field: 'approvedBy', header: 'Approved By', width: 130 },
      { field: 'status', header: 'Status', type: 'status', width: 120 },
    ],
    stats: [
      { key: 'total', label: 'Total Transfers', format: 'number' },
      { key: 'pending', label: 'Pending', format: 'number' },
      { key: 'inTransit', label: 'In Transit', format: 'number' },
      { key: 'completed', label: 'Completed', format: 'number' },
    ],
    formFields: [],
    entityName: 'Transfer',
    statuses: ['pending', 'approved', 'in_transit', 'completed', 'cancelled'],
    chartType: 'area', chartTitle: 'Transfer Trend', showChart: true,
  }],
  ['stock-management-low-stock', 'Low Stock', 'inventory', 'inventory', {
    subtitle: 'Monitor products below reorder level',
    columns: [
      { field: 'name', header: 'Product', flex: 1 },
      { field: 'code', header: 'SKU', width: 110 },
      { field: 'category', header: 'Category', width: 120 },
      { field: 'warehouse', header: 'Warehouse', width: 140 },
      { field: 'stock', header: 'Available Qty', type: 'number', width: 110 },
      { field: 'minStock', header: 'Reorder Level', type: 'number', width: 110 },
      { field: 'status', header: 'Stock Status', type: 'status', width: 120 },
    ],
    stats: [
      { key: 'total', label: 'Total Products', format: 'number' },
      { key: 'lowStock', label: 'Low Stock', format: 'number' },
      { key: 'overdue', label: 'Out of Stock', format: 'number' },
      { key: 'totalStock', label: 'Total Stock', format: 'number' },
    ],
    formFields: [
      { name: 'name', label: 'Product', type: 'text', required: true },
      { name: 'minStock', label: 'Reorder Level', type: 'number', required: true },
      { name: 'warehouse', label: 'Warehouse', type: 'select', options: [
        { value: 'Main Warehouse', label: 'Main Warehouse' },
        { value: 'Cold Storage', label: 'Cold Storage' },
        { value: 'Depot North', label: 'Depot North' },
        { value: 'Depot South', label: 'Depot South' },
      ]},
    ],
    entityName: 'Product',
    statuses: ['low_stock', 'overdue', 'active'],
    showChart: false,
  }],
  ['stock-management-batch-management', 'Batch Management', 'inventory', 'inventory', {
    subtitle: 'Track and manage inventory batches',
    columns: [
      { field: 'batch', header: 'Batch Number', width: 130 },
      { field: 'name', header: 'Product', flex: 1 },
      { field: 'warehouse', header: 'Warehouse', width: 140 },
      { field: 'batchStockCount', header: 'Quantity', type: 'number', width: 100 },
      { field: 'batchDate', header: 'Mfg Date', type: 'date', width: 110 },
      { field: 'expiry', header: 'Expiry Date', type: 'date', width: 110 },
      { field: 'status', header: 'Status', type: 'status', width: 100 },
    ],
    stats: [
      { key: 'total', label: 'Total Batches', format: 'number' },
      { key: 'active', label: 'Active', format: 'number' },
      { key: 'overdue', label: 'Expired', format: 'number' },
      { key: 'totalStock', label: 'Total Qty', format: 'number' },
    ],
    formFields: [
      { name: 'name', label: 'Product Name', type: 'text', required: true },
      { name: 'batch', label: 'Batch Number', type: 'text', required: true },
      { name: 'warehouse', label: 'Warehouse', type: 'select', required: true, options: [
        { value: 'Main Warehouse', label: 'Main Warehouse' },
        { value: 'Cold Storage', label: 'Cold Storage' },
        { value: 'Depot North', label: 'Depot North' },
        { value: 'Depot South', label: 'Depot South' },
      ]},
      { name: 'batchStockCount', label: 'Quantity', type: 'number', required: true },
      { name: 'batchDate', label: 'Manufacturing Date', type: 'date', required: true },
      { name: 'expiry', label: 'Expiry Date', type: 'date' },
    ],
    entityName: 'Batch',
    statuses: ['active', 'low_stock', 'overdue'],
    showChart: false,
  }],
  ['stock-management-expiry-report', 'Expiry Report', 'report', 'inventory', {
    subtitle: 'Track expired and soon-to-expire products',
    columns: [
      { field: 'name', header: 'Product', flex: 1 },
      { field: 'batch', header: 'Batch Number', width: 130 },
      { field: 'warehouse', header: 'Warehouse', width: 140 },
      { field: 'batchStockCount', header: 'Quantity', type: 'number', width: 90 },
      { field: 'batchDate', header: 'Mfg Date', type: 'date', width: 110 },
      { field: 'expiry', header: 'Expiry Date', type: 'date', width: 110 },
      { field: 'daysRemaining', header: 'Days Left', type: 'number', width: 90 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    stats: [
      { key: 'total', label: 'Total Products', format: 'number' },
      { key: 'overdue', label: 'Expired', format: 'number' },
      { key: 'lowStock', label: 'Expiring ≤ 7 Days', format: 'number' },
      { key: 'pending', label: 'Expiring ≤ 30 Days', format: 'number' },
    ],
    formFields: [],
    sumFields: ['batchStockCount'],
    statuses: ['active', 'low_stock', 'pending', 'overdue'],
    showChart: false,
  }],
  ['stock-management-warehouse', 'Warehouse', 'inventory', 'inventory', {
    subtitle: 'Manage warehouse locations, capacity, and stock summary',
    columns: [
      { field: 'name', header: 'Warehouse Name', flex: 1 },
      { field: 'code', header: 'Code', width: 100 },
      { field: 'manager', header: 'Manager', width: 140 },
      { field: 'phone', header: 'Contact', width: 130 },
      { field: 'location', header: 'Location', width: 130 },
      { field: 'stockRooms', header: 'Total Products', type: 'number', width: 120 },
      { field: 'amount', header: 'Stock Value', type: 'currency', width: 130 },
      { field: 'status', header: 'Status', type: 'status', width: 100 },
    ],
    stats: [
      { key: 'total', label: 'Total Warehouses', format: 'number' },
      { key: 'totalStock', label: 'Total Products', format: 'number' },
      { key: 'totalAmount', label: 'Stock Value', format: 'currency' },
      { key: 'active', label: 'Active Warehouses', format: 'number' },
    ],
    formFields: [
      { name: 'name', label: 'Warehouse Name', type: 'text', required: true },
      { name: 'code', label: 'Warehouse Code', type: 'text', required: true },
      { name: 'manager', label: 'Warehouse Manager', type: 'text' },
      { name: 'phone', label: 'Contact Number', type: 'text' },
      { name: 'location', label: 'Location / Address', type: 'textarea' },
      { name: 'stockRooms', label: 'Capacity (Units)', type: 'number' },
    ],
    entityName: 'Warehouse',
    statuses: ['active', 'cancelled'],
    showChart: false,
  }],
  // Route Sales
  ['route-sales-dashboard', 'Route Dashboard', 'route', 'route'],
  ['route-sales-route-assignment', 'Route Assignment', 'route', 'route', { documentedFlow: 'multi-assign-route' as const }],
  ['route-sales-todays-routes', "Today's Routes", 'route', 'route', { documentedFlow: 'live-route' as const }],
  ['route-sales-weekly-schedule', 'Weekly Schedule', 'route', 'route', { documentedFlow: 'weekly-schedule' as const }],
  ['route-sales-outlet-registration', 'Outlet Registration', 'customer', 'route', { documentedFlow: 'register-outlet' as const }],
  ['route-sales-visit-history', 'Visit History', 'route', 'route'],
  ['route-sales-route-tracking', 'Route Tracking', 'tracking', 'tracking'],
  ['route-sales-route-performance', 'Route Performance', 'report', 'route', {
    features: ['routeOrderPerformance', 'reportTotals'],
    columns: [
      { field: 'orderNo', header: 'Order No.', width: 120 },
      { field: 'customer', header: 'Customer', flex: 1 },
      { field: 'salesman', header: 'Salesperson', width: 140 },
      { field: 'route', header: 'Route', width: 130 },
      { field: 'amount', header: 'Order Value', type: 'currency', width: 120 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['amount'],
    chartTitle: 'Order Performance Trend',
    showChart: true,
  }],
  ['route-sales-attendance', 'Attendance', 'hr', 'hr'],
  ['route-sales-customer-visits', 'Customer Visits', 'route', 'route'],
  ['route-sales-gps-tracking', 'GPS Tracking', 'tracking', 'tracking'],
  ['route-sales-collections', 'Collections', 'ledger', 'ledger'],
  ['route-sales-expenses', 'Expenses', 'ledger', 'ledger', {
    columns: [
      { field: 'code', header: 'Voucher', width: 110 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'account', header: 'Expense Head', flex: 1 },
      { field: 'narration', header: 'Narration', width: 180 },
      { field: 'debit', header: 'Amount', type: 'currency', width: 110 },
      { field: 'status', header: 'Status', type: 'status', width: 100 },
    ],
    formFields: [
      { name: 'account', label: 'Expense Head', type: 'select', required: true, options: [
        { value: 'Fuel', label: 'Fuel' },
        { value: 'Travel', label: 'Travel' },
        { value: 'Meals', label: 'Meals' },
        { value: 'Maintenance', label: 'Maintenance' },
        { value: 'Miscellaneous', label: 'Miscellaneous' },
      ]},
      { name: 'debit', label: 'Amount', type: 'number', required: true },
      { name: 'narration', label: 'Narration', type: 'textarea', required: true },
      { name: 'date', label: 'Date', type: 'date', required: true },
    ],
    entityName: 'Expense',
  }],
  ['route-sales-route-sales-report', 'Route Sales Report', 'report', 'route', {
    columns: [
      { field: 'code', header: 'Route', width: 100 },
      { field: 'name', header: 'Route Name', flex: 1 },
      { field: 'salesman', header: 'Salesman', width: 140 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'visited', header: 'Visited', type: 'number', width: 90 },
      { field: 'outlets', header: 'Outlets', type: 'number', width: 90 },
      { field: 'collections', header: 'Collection', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['visited', 'outlets', 'collections'],
  }],
  // Customers
  ['customers-customer-list', 'Customers', 'customer', 'customer'],
  ['customers-customer-profile', 'Customer Profiles', 'customer', 'customer'],
  ['customers-outstanding', 'Outstanding', 'customer', 'customer'],
  ['customers-credit-limit', 'Credit Limits', 'customer', 'customer'],
  ['customers-customer-ledger', 'Customer Ledger', 'ledger', 'ledger'],
  ['customers-visit-history', 'Visit History', 'route', 'route'],
  ['customers-customer-location', 'Customer Locations', 'tracking', 'tracking'],
  // HR
  ['hr-employees', 'Employees', 'hr', 'hr', { documentedFlow: 'employee-directory' as const }],
  ['hr-attendance', 'Attendance', 'hr', 'hr', { documentedFlow: 'attendance' as const }],
  ['hr-payroll', 'Payroll', 'hr', 'hr', { documentedFlow: 'payroll' as const }],
  ['hr-incentives', 'Incentives', 'hr', 'hr'],
  ['hr-sales-targets', 'Sales Targets', 'hr', 'hr'],
  ['hr-performance', 'Performance', 'hr', 'hr', { documentedFlow: 'performance' as const }],
  ['hr-leave-management', 'Leave Management', 'hr', 'hr', { documentedFlow: 'leave-registry' as const }],
  ['hr-roles-permissions', 'Roles & Permissions', 'settings', 'hr', { documentedFlow: 'roles-access' as const }],
  // Logistics
  ['logistics-delivery-schedule', 'Delivery Schedule', 'logistics', 'logistics'],
  ['logistics-dispatch', 'Dispatch', 'logistics', 'logistics'],
  ['logistics-vehicle-management', 'Vehicles', 'logistics', 'logistics'],
  ['logistics-driver-management', 'Drivers', 'hr', 'logistics'],
  ['logistics-live-tracking', 'Live Tracking', 'tracking', 'tracking'],
  ['logistics-e-way-bills', 'E-Way Bills', 'logistics', 'logistics', {
    documentedFlow: 'e-way-bill' as const,
    subtitle: 'Generate and manage GST E-Way Bills for deliveries',
    columns: [
      { field: 'ewayBill', header: 'EWB Number', width: 130 },
      { field: 'code', header: 'Delivery Ref', width: 120 },
      { field: 'vehicle', header: 'Vehicle', width: 120 },
      { field: 'driver', header: 'Driver', width: 130 },
      { field: 'customer', header: 'Consignee', flex: 1 },
      { field: 'distance', header: 'Distance', width: 100 },
      { field: 'amount', header: 'Invoice Value', type: 'currency', width: 120 },
      { field: 'date', header: 'Valid From', type: 'date', width: 110 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    formFields: [
      { name: 'vehicle', label: 'Vehicle No.', type: 'text', required: true },
      { name: 'driver', label: 'Driver', type: 'text', required: true },
      { name: 'customer', label: 'Consignee', type: 'text', required: true },
      { name: 'amount', label: 'Invoice Value (₹)', type: 'number', required: true },
      { name: 'distance', label: 'Distance (km)', type: 'text' },
      { name: 'date', label: 'Valid From', type: 'date', required: true },
    ],
    entityName: 'E-Way Bill',
  }],
  // Reports
  ['reports-sales-report', 'Sales Report', 'report', 'sales', {
    columns: [
      { field: 'code', header: 'Order No.', width: 120 },
      { field: 'customer', header: 'Customer Name', flex: 1 },
      { field: 'salesman', header: 'Salesperson Name', width: 150 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'quantity', header: 'Qty', type: 'number', width: 80 },
      { field: 'amount', header: 'Amount', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['quantity', 'amount'],
  }],
  ['reports-purchase-report', 'Purchase Report', 'report', 'purchase', {
    columns: [
      { field: 'code', header: 'PO Ref', width: 120 },
      { field: 'supplier', header: 'Supplier', flex: 1 },
      { field: 'particulars', header: 'Description', width: 180 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'items', header: 'Items', type: 'number', width: 80 },
      { field: 'amount', header: 'Amount', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['items', 'amount'],
  }],
  ['reports-collection-report', 'Collection Report', 'report', 'ledger', {
    columns: [
      { field: 'code', header: 'Ref', width: 120 },
      { field: 'customer', header: 'Customer', flex: 1 },
      { field: 'route', header: 'Route', width: 140 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'amount', header: 'Collected', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['amount'],
  }],
  ['reports-expense-report', 'Expense Report', 'report', 'ledger', {
    columns: [
      { field: 'code', header: 'Voucher', width: 120 },
      { field: 'account', header: 'Expense Head', flex: 1 },
      { field: 'narration', header: 'Narration', width: 200 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'debit', header: 'Amount', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['debit'],
  }],
  ['reports-route-report', 'Route Report', 'report', 'route', {
    columns: [
      { field: 'code', header: 'Route', width: 100 },
      { field: 'name', header: 'Route Name', flex: 1 },
      { field: 'salesman', header: 'Salesman', width: 140 },
      { field: 'date', header: 'Date', type: 'date', width: 110 },
      { field: 'visited', header: 'Visited', type: 'number', width: 90 },
      { field: 'outlets', header: 'Outlets', type: 'number', width: 90 },
      { field: 'collections', header: 'Collection', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['visited', 'outlets', 'collections'],
  }],
  ['reports-product-report', 'Product Report', 'report', 'inventory', {
    columns: [
      { field: 'code', header: 'SKU', width: 110 },
      { field: 'name', header: 'Product', flex: 1 },
      { field: 'category', header: 'Category', width: 120 },
      { field: 'brand', header: 'Brand', width: 100 },
      { field: 'stock', header: 'Stock', type: 'number', width: 90 },
      { field: 'amount', header: 'Value', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['stock', 'amount'],
  }],
  ['reports-employee-report', 'Employee Report', 'report', 'hr', {
    columns: [
      { field: 'code', header: 'ID', width: 100 },
      { field: 'name', header: 'Employee', flex: 1 },
      { field: 'department', header: 'Department', width: 120 },
      { field: 'role', header: 'Role', width: 140 },
      { field: 'attendance', header: 'Attendance', width: 110 },
      { field: 'salary', header: 'Salary', type: 'currency', width: 110 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['salary'],
  }],
  ['reports-profit-loss', 'Profit & Loss', 'report', 'ledger', { features: ['reportTotals', 'chartTypeSwitch'], sumFields: ['debit', 'credit'], chartTitle: 'P&L Analysis' }],
  ['reports-balance-sheet', 'Balance Sheet', 'report', 'ledger', {
    columns: [
      { field: 'code', header: 'Ref', width: 120 },
      { field: 'particulars', header: 'Account', flex: 1 },
      { field: 'date', header: 'As On', type: 'date', width: 110 },
      { field: 'debit', header: 'Debit', type: 'currency', width: 120 },
      { field: 'credit', header: 'Credit', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    features: ['reportTotals'],
    sumFields: ['debit', 'credit'],
  }],
  ['reports-cash-flow', 'Cash Flow', 'report', 'ledger', {
    columns: [
      { field: 'code', header: 'Ref', width: 120 },
      { field: 'particulars', header: 'Activity', flex: 1 },
      { field: 'date', header: 'Period', type: 'date', width: 110 },
      { field: 'debit', header: 'Inflow', type: 'currency', width: 120 },
      { field: 'credit', header: 'Outflow', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    features: ['reportTotals'],
    sumFields: ['debit', 'credit'],
  }],
  ['reports-gst-report', 'GST Report', 'report', 'ledger', {
    columns: [
      { field: 'code', header: 'GST Ref', width: 100 },
      { field: 'party', header: 'Party', flex: 1 },
      { field: 'period', header: 'Period', width: 100 },
      { field: 'taxable', header: 'Taxable', type: 'currency', width: 110 },
      { field: 'cgst', header: 'CGST', type: 'currency', width: 90 },
      { field: 'sgst', header: 'SGST', type: 'currency', width: 90 },
      { field: 'total', header: 'Total', type: 'currency', width: 110 },
    ],
    sumFields: ['taxable', 'cgst', 'sgst', 'total'],
  }],
  ['reports-inventory-report', 'Inventory Report', 'report', 'inventory', {
    columns: [
      { field: 'code', header: 'SKU', width: 110 },
      { field: 'name', header: 'Product', flex: 1 },
      { field: 'category', header: 'Category', width: 120 },
      { field: 'brand', header: 'Brand', width: 100 },
      { field: 'stock', header: 'Stock Qty', type: 'number', width: 100 },
      { field: 'amount', header: 'Stock Value', type: 'currency', width: 120 },
      { field: 'status', header: 'Status', type: 'status', width: 110 },
    ],
    sumFields: ['stock', 'amount'],
  }],
  // Admin
  ['admin-users', 'Users', 'hr', 'hr', { entityName: 'User' }],
  ['admin-roles', 'Roles', 'settings', 'hr'],
  ['admin-permissions', 'Permissions', 'settings', 'settings'],
  ['admin-notifications', 'Notifications', 'settings', 'settings'],
  ['admin-ai-assistant-logs', 'AI Assistant Logs', 'settings', 'settings'],
  ['admin-system-settings', 'System Settings', 'settings', 'settings', {
    documentedFlow: 'theme-settings' as const,
    subtitle: 'Appearance, color theme, and portal preferences',
    stats: [],
    showChart: false,
  }],
  ['admin-company-settings', 'Company Settings', 'settings', 'settings'],
  ['admin-backup-restore', 'Backup & Restore', 'settings', 'settings'],
  ['admin-audit-logs', 'Audit Logs', 'settings', 'settings'],
]

export const moduleRegistry = new Map<string, ModuleConfig>(
  registryEntries.map(([slug, title, layout, domain, overrides]) => [
    slug,
    cfg(slug, title, layout, domain, overrides),
  ]),
)

export function getModuleConfig(path: string): ModuleConfig {
  const slug = path.replace(/^\//, '').replace(/\//g, '-')
  return moduleRegistry.get(slug) ?? cfg(slug, 'Module', 'transaction', 'sales')
}

export function pathToSlug(path: string): string {
  return path.replace(/^\//, '').replace(/\//g, '-')
}
