/** CSS variable references — safe in module-level sx objects; update live when theme changes */
export const v = {
  primary: 'var(--rs-primary)',
  primaryLight: 'var(--rs-primary-light)',
  primaryDark: 'var(--rs-primary-dark)',
  secondary: 'var(--rs-secondary)',
  background: 'var(--rs-background)',
  surface: 'var(--rs-surface)',
  surfaceElevated: 'var(--rs-surface-elevated)',
  textPrimary: 'var(--rs-text-primary)',
  textSecondary: 'var(--rs-text-secondary)',
  textMuted: 'var(--rs-text-muted)',
  border: 'var(--rs-border)',
  borderStrong: 'var(--rs-border-strong)',
  success: 'var(--rs-success)',
  successSoft: 'var(--rs-success-soft)',
  warning: 'var(--rs-warning)',
  warningSoft: 'var(--rs-warning-soft)',
  error: 'var(--rs-error)',
  errorSoft: 'var(--rs-error-soft)',
  info: 'var(--rs-info)',
  infoSoft: 'var(--rs-info-soft)',
  coral: 'var(--rs-coral)',
  coralSoft: 'var(--rs-coral-soft)',
  sidebar: 'var(--rs-sidebar)',
  sidebarHover: 'var(--rs-sidebar-hover)',
  sidebarActive: 'var(--rs-sidebar-active)',
  action: 'var(--rs-action)',
  gradientPrimary: 'var(--rs-gradient-primary)',
  gradientAccent: 'var(--rs-gradient-accent)',
  gradientSoft: 'var(--rs-gradient-soft)',
  shadowSm: 'var(--rs-shadow-sm)',
  shadowMd: 'var(--rs-shadow-md)',
  shadowLg: 'var(--rs-shadow-lg)',
} as const

/** Opacity tints that follow live theme CSS variables */
export const mix = {
  primary: (pct: number) => `color-mix(in srgb, ${v.primary} ${pct}%, transparent)`,
  secondary: (pct: number) => `color-mix(in srgb, ${v.secondary} ${pct}%, transparent)`,
  success: (pct: number) => `color-mix(in srgb, ${v.success} ${pct}%, transparent)`,
  error: (pct: number) => `color-mix(in srgb, ${v.error} ${pct}%, transparent)`,
  surface: (pct: number) => `color-mix(in srgb, ${v.primary} ${pct}%, ${v.surface})`,
} as const
